source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'sinatra-partial'
gem 'sinatra-flash'
gem 'haml'
gem 'sinatra-asset-pipeline'
gem 'pry'
gem 'sinatra-websocket', '0.3.1'
gem 'sinatra-contrib'
gem 'bootstrap', '~> 4.0.0.alpha5'
gem 'thin'
gem 'therubyracer'
gem 'haml_coffee_assets'
gem 'elasticsearch', '2.0.0'
#gem 'sqlite3'
#gem 'activerecord', '3.2.17'
#gem 'sinatra-activerecord'
#gem 'compass'

#gem 'font-awesome-sass'
#gem 'dotenv'
#gem 'capistrano'
#gem 'capistrano-passenger'
#gem 'capistrano-rbenv', '~> 2.0'
#gem 'capistrano-bundler'

#gem 'sys-filesystem'
#gem 'rspec'
#gem 'rack-test', :require => "rack/test"
#gem 'simplecov', :require => false
#gem 'capistrano-rails'
